image: hpiswa/smalltalkci

variables:
  COVERAGE_DIR: /builds/pharoproject/coverage

stages:
  - test

run tests:
  stage: test
  script: smalltalkci -s "Pharo64-11.0"
  artifacts:
    paths:
      - $COVERAGE_DIR
